<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>SevenZipExtractor.Tests.Xunit</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <!--
    This template uses native xUnit.net command line options when using 'dotnet run' and
    VSTest by default when using 'dotnet test'. For more information on how to enable support
    for Microsoft Testing Platform, please visit:
      https://xunit.net/docs/getting-started/v3/microsoft-testing-platform
    -->

  <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>


  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

 <ItemGroup>
    <Content Include="Resources/*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>  
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageReference Include="xunit.v3" Version="3.1.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="xunit.v3.assert" Version="3.1.0" />
    <PackageReference Include="xunit.v3.core" Version="3.1.0" />
    <PackageReference Include="xunit.v3.runner.console" Version="3.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\SevenZipExtractor\SevenZipExtractor.csproj" />
  </ItemGroup>
  </Project>
